# Generated by Django 3.2.6 on 2021-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free', '0007_alter_result_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-time'], 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.AlterField(
            model_name='result',
            name='result_type',
            field=models.CharField(choices=[('f', 'Final'), ('p', 'Partial')], max_length=1, verbose_name='Result type'),
        ),
    ]
